services:
  laguidonette:
    image: laguidonette
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,api-docs
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_R2DBC_URL=r2dbc:postgresql://laguidonette-postgresql:5432/LaGuidonette
      - SPRING_LIQUIBASE_URL=jdbc:postgresql://laguidonette-postgresql:5432/LaGuidonette
      - JHIPSTER_SLEEP=30
    ports:
      - '8080:8080'
  laguidonette-postgresql:
    image: postgres:14.5
    environment:
      - POSTGRES_USER=LaGuidonette
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST_AUTH_METHOD=trust
